name: Build wireguard-go mipsle softfloat
on:
  workflow_dispatch: # 手动触发编译

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Clone wireguard-go source
        run: |
          git clone https://git.zx2c4.com/wireguard-go src
          cd src

      - name: Compile wireguard-go
        env:
          GOOS: linux
          GOARCH: mipsle
          GOMIPS: softfloat
        run: |
          cd src
          go build -trimpath -ldflags="-s -w" -o wireguard-go .

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-go-mipsle-softfloat
          path: src/wireguard-go
